### ISSUE TITLE
Make WW error

### ISSUE THREAD

**Issue by davidfarmer** [active-calculus/active-calculus-single-mbx#101]
I pulled the latest Active Calculus and went to make
the html version.  It failed, with errors like

/bin/sh: line 0: cd:
/home/farmer/hosting/source/active-calculus-single-mbx/output/webwork-extraction:
No such file or directory

warning: failed to load external entity
"/home/farmer/hosting/source/active-calculus-single-mbx/output/webwork-extraction/webwork-extraction.xml"

with the second one occurring multiple times.  Then it died with this:

warning: failed to load external entity "/home/farmer/hosting/source/active-calculus-single-mbx/output/webwork-extraction/acs-merge.ptx"
unable to parse /home/farmer/hosting/source/active-calculus-single-mbx/output/webwork-extraction/acs-merge.ptx
make: *** [html] Error 6

So I created the directory mentioned in the first error,
(probably that should be done with an "install" in the Makefile)
did 'make html' again, and again got the second error many times.
But this time it continued, producing:
https://activecalculus.org/single_test/

Not sure what to check to see if it worked properly, and not sure why I don't have
the webwork-extraction.xml file.

**Comment by mitchkeller** [comment]
You need to do the WeBWorK extraction before `make html`. That's `make acs-extraction`. The Makefile creates all the necessary directories, but because the WW extraction takes a fair amount of time and only needs to be done when the selection of WW problems to be included changes, it's a separate target.
