### ISSUE TITLE
Issues with spacing around footnotes

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-single-mbx#190]
The footnote at/around line 222 in sec-4-1-velocity-distance.xml winds up output with an extra space before it. This may be the result of some of the pretty printing that @davidfarmer does, but I can't say for sure. Right now, the footnote appears to be floating in the middle of the sentence.

![image](https://user-images.githubusercontent.com/8580151/47858270-b3cc5080-ddb9-11e8-867a-bcb294ae3145.png)

**Comment by mitchkeller** [comment]
Something also looks amiss with the spacing around the footnote mark in Example 5.4.1. The u=x equation that follows immediately looks too close, as if there is no spacing on either side of the footnote.

This and the earlier report on this issue could have been improved by the pretty printing that was done to the edition branch in preparation for the S19 UTMOST study.

**Comment by davidfarmer** [comment]
Prettyprinting of footnotes has changed since AC was prettyprinted.
One problem is that the whitespace around footnotes depends on context.
For example, an author might put a footnote immediately before a comma,
and another might put one immediately after a period.   The prettyprinting script
now leaves the whitespace around a footnote as the author wrote it.  So it would be good
to go through the source and adjust as needed.

There may be a separate issue with footnotes immediately before inline math.

**Comment by mattboelkins** [comment]
I'm a little perplexed by the first example Mitch notes, since in the source code, it reads:

      In addition, we observe<fn>
      Here we are making the

It would seem like there has to be a space between "observe" and "<fn>" in order to generate the noted error.  I'm on the master branch.

**Comment by mitchkeller** [comment]
David redid the prettyprinting in November, which would have been after we published the 2018 edition. Let's leave this issue open and assign it to me. I can go through and grep for all of the `<fn>` and `</fn>` tags over the summer and check for sane spacing around them. If anything is incorrect, I'll let David know in case there's something he can do so his script handles that particular case better.

**Comment by mattboelkins** [comment]
Thanks Mitch.

**Comment by mitchkeller** [comment]
The footnotes all look correct in source now with one revision I just made and pushed. For @davidfarmer's reference, the problematic bit was `</fn>(such as books on a shelf)`. I have not re-run the prettyprinter to see if it now makes that mistake, but perhaps some testing would be in order.

**Comment by mitchkeller** [comment]
Closed by PR #218
