### ISSUE TITLE
Activity 4.3.3(e) mismatched to its solution

### ISSUE THREAD

**Issue by mikeshulman** [active-calculus/active-calculus-single-mbx#195]
Activity 4.3.3(e) asks to integrate 2x^3-7g(x).  But the answer and solution are given as if the question were to integrate 2x^2-7g(x).  I believe the correct answer for integrating 2x^3-7g(x) ought to be -583/2.

**Comment by mattboelkins** [comment]
Mike, thanks for pointing this out.  On my list.

Matt
