### ISSUE TITLE
Webwork exercises that are incompatible with PDF output

### ISSUE THREAD

**Issue by mikeshulman** [active-calculus/active-calculus-single-mbx#199]
As noted at #194, there are some webwork exercises that fail to compile in the PDF output.  Here is a list of their IDs:

* ez-1-1-WW5
* ez-1-4-WW3
* ez-2-3-WW8
* ez-2-8-WW1
* ez-4-2-WW1
* ez-4-2-WW2
* ez-4-3-WW4
* ez-5-6-WW8
* ez-7-2-WW2

**Comment by mitchkeller** [comment]
Thanks, @mikeshulman. As a first step, @mattboelkins can you see if any of these have comparable exercises in the OPL that could be tried as replacements? For any that do have suitable replacements, maybe let's track what they would be on this issue. For those that don't, just make a note and I will look at them a bit later to see if they can be recoded in PTX.

**Comment by mitchkeller** [comment]
Through the magic of waiting for PreTeXt to get better (or someone to improve the problems in the OPL), these exercises are all now compatible with PDF output.

There are four WW exercises in 4.4, however (3–6) that are problematic for PDF output. The PDF now builds, but an error message is put in the place of the exercise text. I'm going to continue to use this issue for tracking the problem with those four exercises.

**Comment by mitchkeller** [comment]
The four exercises in 4.4 are now coded in PTX source and work properly. There is one exercise that does something a bit odd and I've chawed to make it work for the 2018 updated edition. Will come back to this once that has been put to bed fully.

**Comment by mitchkeller** [comment]
The remaining problematic exercise is `Library/Rochester/setDiffEQ2DirectionFields/ur_de_2_3.pg`. It compiles, but there are images missing in the PDF output at the moment. (Manually fixed so that 2018-updated is fine.)

**Comment by mitchkeller** [comment]
This seems to be solved.
