### ISSUE TITLE
Typo in 6.4

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-single-mbx#204]
In the introduction to 6.4, "from physics, a basic principal is that work is the product of force and distance" has a mistake. The correct word is "principle".

**Comment by mattboelkins** [comment]
I groaned aloud when I saw this error.  Thanks Mitch.

**Comment by mitchkeller** [comment]
I figured you would, since the correct word was used elsewhere. 

Assume my careful proofreading will drop off again after 6.4, since I won't teach Chapter 7 and I'm reasonably comfortable with Chapter 8. But this physics stuff is not in my wheelhouse at all.
