### ISSUE TITLE
Gravitational constant in SI units and Activity 6.4.3

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-single-mbx#206]
In the discussion before Activity 6.4.3, it is claimed that a = 9.81 N/kg^3. Should that be N/kg?

The solution/answer to part a of activity 6.4.3 seem to use 9800 N/m^3 for the weight density of water instead of the 9810 N/m^3 that would be arrived at my using 9.81 for a.

**Comment by mitchkeller** [comment]
The answer/solution to Activity 6.4.3 part (a) seems to be wrong in that it uses incorrect limits of integration. Since the tank is six feet tall but only contains four feet of water, it is incorrect to use [0,1] as the interval of integration, or at least it seems to me.

**Comment by mattboelkins** [comment]
Thanks Mitch.  Those limits should have been x=2 to x=3 since the top 1 foot of water is being pumped out.  And right about 9.81 vs 9.8.
