### ISSUE TITLE
Problematic sentence in 8.3

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-single-mbx#209]
The third sentence of the paragraph before Activity 8.3.2 includes the phrase "The definite integral is the sum of an infinite collections of numbers,". There's a grammar issue in that sentence that definitely needs resolution. Given the way the definite integral is defined earlier, I'm not sure that I agree that this phrase is accurate, however. I like the call back to definite integrals, but it seems inaccurate to write this here given that the definite integral is defined as the limit of a sequence of finite sums.

**Comment by mattboelkins** [comment]
Good points here.  Thanks Mitch.
