### ISSUE TITLE
brackets around the thing being differentiated

### ISSUE THREAD

**Issue by davidfarmer** [active-calculus/active-calculus-single-mbx#211]
This is mostly a question, but could become an issue depending on the answer.

It seems that whenever something is being operated on by \frac{d}{dx},
that think is surrounded by square brackets.  Not parentheses, and not
nothing (meaning no brackets, even when those brackets are not strictly
necessary.

I'd like to know the extent to which this is content vs. presentation.
If a publisher came out with a version that used parentheses, or eliminated
those brackets (when possible), would that be okay?

The precise version of my question is below, but please ignore that version
if it makes things less clear.

I am developing a way to mark up mathematical content.  The mathematical
content of this expression:

   \frac{d}{dx} [ 5x^2 ]

is

(differentiate with respect to x)  (the quantity)  (5x^2).
(Not the actual notation, Those parentheses are delimiters, not content.)

The "mathematical version" does not say anything about the use of
square brackets, nor that when rendered there needs to be anything
surrounding the 5x^2.

My question:  is it completely a rendering issue, which can be set
globally for the whole book, to wrap the argument of d/dx in square
brackets?  Or does the source need to know something about that?

**Comment by davidfarmer** [comment]
Let me contrast this with another instance, where the source does need to
be different.

Usually multiplication is implied:  f(x) g(x) means f(x) times g(x).  But occasionally
(see Section 2.3 for several examples) you write f(x) \cdot g(x) .  The mathematical
meaning is the same as f(x) g(x), but the author asserts that the text should explicitly
show that two quantities are being multiplied.  That is valuable information and needs to
be preserved by any alternate way of marking up the mathematical content.

**Comment by mattboelkins** [comment]
> If a publisher came out with a version that used parentheses, or eliminated those brackets (when possible), would that be okay?

I'd say "No, that's not ok."  I think the brackets are completely essential.  And I think the square ones are essential to indicate that it's a different situation than just "grouping".

> My question: is it completely a rendering issue, which can be set
globally for the whole book, to wrap the argument of d/dx in square
brackets? 

That would be a completely fine approach.  The source need not know.  I want that notation used globally.

> Usually multiplication is implied: f(x) g(x) means f(x) times g(x). But occasionally
(see Section 2.3 for several examples) you write f(x) \cdot g(x) . The mathematical
meaning is the same as f(x) g(x), but the author asserts that the text should explicitly
show that two quantities are being multiplied. That is valuable information and needs to
be preserved by any alternate way of marking up the mathematical content.

I am all for making the implicit explicit, so having it always be f(x) \cdot g(x) would be good by me.  You'll notice that I always use \sin(x) and never \sin x, even though the latter is prevalent in a lot of texts.  Ditto \ln(x).

**Comment by davidfarmer** [comment]
> I am all for making the implicit explicit, so having it always be f(x) \cdot g(x) would be good by
> me. You'll notice that I always use \sin(x) and never \sin x, even though the latter is prevalent in
> a lot of texts. Ditto \ln(x).

I definitely don't want to always put the dot since it adds a lot of
visual noise if used routinely.  I like how it is occasionally used to
make a point.

There are at least 3 places where you don't put the parentheses
around the argument of a trig function!  Consider it a scavenget hunt.
