### ISSUE TITLE
weird repeat of two paragraphs in PDF

### ISSUE THREAD

**Issue by mattboelkins** [active-calculus/active-calculus-single-mbx#212]
In the PDF produced in July/August 2018, there's a strange output error.  On the bottom of p. 14, there are two paragraphs that respectively begin, "From Table 1.2.5 ..." and "The situation is more complicated ..."  Each of these appear just once in the source code.  But in the PDF, following Table 1.2.5 on p. 15, these exact same two paragraphs get repeated.  The error doesn't appear in the HTML.  @mitchkeller I assume this had to happen with something manual in PDF production.

**Comment by mitchkeller** [comment]
Yeah, I can see how this would have gotten introduced when dealing with some merge conflict issues as I worked through the page layout. I'm going to let this sit until we're ready to do the next round of PDF production. I'm hoping it's not too painful.

**Comment by mitchkeller** [comment]
This is resolved in the production for the updated 2018.
