### ISSUE TITLE
LaTeX version of PA 1.2.1 part b

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-single-mbx#229]
Something got messed up with a LaTeX command in this preview activity and there's pure gibberish spewed out at the end where a `fillin` should be in use.

@mattboelkins I should be able to easily fix the PDF for this without messing up pagination. Would you like that for both Scholarworks and KDP, only one of the two, or neither?

**Comment by mattboelkins** [comment]
@mitchkeller <https://github.com/mitchkeller>  Sometime soon I'd like the
Scholarworks one; I want to wait til KDP sales quiet down before fising it
in the KDP one (which will also need the activities workbook).  Is this the
only such fillin that got messed up, or might there be others?

The HTML is right, so I don't view this as urgent.

Thanks,
Matt

**Comment by mitchkeller** [comment]
I'm going to close this, since we 2018-updated is pretty well locked for PDF/print.
