### ISSUE TITLE
Preview Activity 2.5.1(c)

### ISSUE THREAD

**Issue by mikeshulman** [active-calculus/active-calculus-single-mbx#236]
Presumably the intent is that (tan(x))^2 is a composite of basic functions.  At least, that's what the webwork version of this activity considers the correct answer.  But it can also be written as tan(x)*tan(x), which is a product of basic functions.  Is that an intended ambiguity?  If so, should the webwork version accept both as correct?  If not, the function could be changed to something like (tan(x))^3.

**Comment by mitchkeller** [comment]
I personally like the ambiguity. We don't maintain the WeBWorK versions of the Preview Activities.

**Comment by mikeshulman** [comment]
@mitchkeller Would you recommend then that the webwork version of the activity accept both answers as correct?  I could easily submit such a suggested change to the preview activities in the webwork OPL.

**Comment by mitchkeller** [comment]
That would be my suggestion. I'm not sure if @mattboelkins has an official stance on a "right" answer here or not.

**Comment by mattboelkins** [comment]
I think WeBWorK should accept both, as the ambiguity is fine.

David Hunter <dhunter@westmont.edu> and Branden Stone <bstone@hamilton.edu>
are the authors behind the WW Preview Activities.  I'm sure they'd welcome
hearing from you directly with this request.

Thanks Mike,
Matt

**Comment by mikeshulman** [comment]
Now fixed in the OPL.
