### ISSUE TITLE
Derivative notation in section 2.6

### ISSUE THREAD

**Issue by mikeshulman** [active-calculus/active-calculus-single-mbx#237]
Why do the examples and activities in section 2.6 introduce new names for the inverse functions?  E.g. in section 2.6.2 we let g(x) = ln(x), compute the derivative of g(x), using at one point the fact that g(x)=ln(x), and then call the result the derivative of ln(x).  Is there a reason for introducing g, rather than just working with ln all the way through?  This has always been confusing for my students.

This year I tried doing it in class without g, just writing ln'(x) instead of g'(x), and they seemed to get it much quicker; I similarly rewrote activity 2.6.3 writing arctan'(x) instead of r'(x), and they had a much easier time focusing on the important parts.  I've asked around and some of my colleagues find it unusual to put a prime on a multi-character identifier like ln or arctan, but no one voiced any objection to the practice.  Is there another reason for the g?

**Comment by mitchkeller** [comment]
I can't say that I've run into any issues with this. I like that it reduces temptation to simplify things and emphasizes the connection to the chain rule: There's an inside function there. Use the chain rule to differentiate. Now let's go back and think about what that is the derivative of.

**Comment by mikeshulman** [comment]
For whatever it's worth, none of my students did any mistaken simplification.  I don't see any closer connection to the chain rule by calling the inside function "g" than by calling it "ln" -- at this point they've been using the chain rule for plenty of concrete functions as well as abstract ones.

**Comment by mattboelkins** [comment]
I've never seen anyone use the notation $\ln'(x)$ nor, say $\sin'(x)$.  I
guess I get why that might be simple for students, but I actually think
it's poor use of derivative notation and not something to encourage.  (E.g.
given a function $f$, it's valid to talk about $f$ and $f'$ without writing
"(x)".  But for "sin", it's nonstandard to refer to "sin" or "sin' "
without an argument.)

I'm way more comfortable with statements like, "if $f(x) = \sin(x)$, then
$f'(x) = \cos(x)$.

I also want to emphasize the role of composition in inverses, so
distinguishing f and g is important.

If you want to avoid the f and g notation, Leibniz notation for the
derivative would be fine:  $\frac{d}{dx}[ln(x)]$, etc.  I can see writing
the content in Section 2.6.2 in a style like

  $\frac{d}{dx}[ e^{\ln(x)} ]= e^{\ln(x)} \frac{d}{dx}[\ln(x)]$

and from there solving for  4\frac{d}{dx}[\ln(x)]$

MB

**Comment by mikeshulman** [comment]
Maybe it's nonstandard, but is there anything objectively wrong with it?  I don't see any potential for confusion.

I don't understand what you mean about distinguishing f and g, can you explain?

**Comment by mattboelkins** [comment]
In the setting of inverse functions, their composition is the identity
mapping.  A key perspective for students to grasp -- not just for calculus,
but in courses like geometry, linear algebra, and modern algebra -- is that
an inverse function undoes the effect of the original function.  To that
end, thinking about the processes labeled f and g as compared to the
process f \circ g is key.  For functions like $f(x) = e^x$ and $g(x) =
\ln(x)$, I doubt that many students really recognize that function
composition is at work when you write $e^{\ln(x)}$, whereas writing
$f(g(x)) = f(\ln(x)) = e^{\ln(x)}$ emphasizes this fact.

If you don't label a function like e^{x} as $f(x) = e^{x}$, how do you
label its inverse?  And how do you label its derivative?  You wouldn't want
to use "$e'^{x}$" for the derivative, nor $e^{-1(x)}$ for the inverse.  In
both contexts, I see $f$, $f'$, and $f^{-1}$ as essential clarifying
notation.  And if we need that for the original exponential function, it
makes sense to do similarly for the inverse function, $g(x) = \ln(x)$.

**Comment by mikeshulman** [comment]
But the calculation of the derivative of ln(x) at the beginning of section 2.6.2 does not currently use a name like f(x) for the function e^x.  It introduces a name g(x)=ln(x), but then uses Leibniz notation to take the derivative of e^{g(x)}.  I don't see why it should be easier to see e^{g(x)} as a function composition than e^{ln(x)}.

I certainly agree that it can be useful to have a name for a function like e^x, since we can't apply function-based notations like primes and inverses to the notation e^x (since, of course, "e" is not the name of the function).  But since ln doesn't suffer from the same flaws -- its standard notation *is* one that we can apply primes and inverses to without fear of confusion -- why should we force ourselves to introduce a new name for it?  (And of course, in the case of trig functions the original ones sin and cos are already written using function notation, while even the exponential function does have a less-common but still fairly standard function notation exp(x) = e^x.)

**Comment by mattboelkins** [comment]
> It introduces a name g(x)=ln(x), but then uses Leibniz notation to take
the derivative of e^{g(x)}. I don't see why it should be easier to see
e^{g(x)} as a function composition than e^{ln(x)}.

I see your point here.

I guess it comes down to me having never considered the notation
$\ln'(x)$.  As I mentioned earlier, I've never seen anyone else use it.  My
initial reaction to it is negative, but that doesn't mean I'm right.  I'll
think about it :-).

Mike, I always appreciate your comments and feedback on the text.

Matt

**Comment by mikeshulman** [comment]
My initial reaction to it was negative as well, but after I thought about it I couldn't think of any actual problem with it.  I'll be interested to hear your conclusion.

I hope I don't come off as too critical.  I'm very happy with Active Calculus and what my calculus courses have become through using it, and very grateful to you for all the effort you've put into creating this great resource!  I'm just suggesting what I see as a few potential improvements here and there (and learning through the conversation as well myself).

**Comment by mattboelkins** [comment]
> I hope I don't come off as too critical. I'm very happy with Active
Calculus and what my calculus courses have become through using it, and
very grateful to you for all the effort you've put into creating this great
resource! I'm just suggesting what I see as a few potential improvements
here and there (and learning through the conversation as well myself).

You don't.

I hope I don't come off as too defensive.  Email is a lousy medium, and I'm
usually writing at the end of long days :-).  I really appreciate the
suggestions for improvement.

Are you going to be at JMM?  It would be great to talk about this over
beverages.

Matt

**Comment by mikeshulman** [comment]
Unfortunately, not this year.

**Comment by mikeshulman** [comment]
Does closing this issue indicate that you've decided against my suggestion?
