### ISSUE TITLE
Math inside \text{}

### ISSUE THREAD

**Issue by rbeezer** [active-calculus/active-calculus-single-mbx#242]
Hopefuily this is not noise, since I'd think you'd be on it.  Hitting

```latex
f(x) = \begin{cases}3(x+2)+2 \amp  \text{ for -3 \lt  x \lt  -2 }  \\
        \frac{2}{3}(x+2)+1 \amp  \text{ for -2 \le x \lt  -1 }  \\
        \frac{2}{3}(x+2)+1 \amp  \text{ for -1 \lt  x \lt  1 }  \\
        2 \amp  \text{ for x = 1 }  \\
        4-x \amp  \text{ for x \gt 1 }
        \end{cases}
```
as part of braille testing, and the `\lt` inside `\text{}` are provoking a `pdflatex` error.

I'll hand-edit what I have right now - no urgency, I won't consult source again.

**Comment by rbeezer** [comment]
Addressed in the PreTeXt Guide. (Mostly a note for myself.)

**Comment by mitchkeller** [comment]
Fixed on a branch.
