### ISSUE TITLE
WebWork problems are hidden 

### ISSUE THREAD

**Issue by kentemorrison** [active-calculus/active-calculus-single-mbx#26]
When I make the html the WebWork problems are hidden. The titles are there but clicking on the WebWork exercise phrase opens up the knowl without the exercise text. I expect that one or more of the string parameters used with xsltproc in the makefile must be set to 'yes'--but which ones? Or is it something else?  I'd like to see how the titles work with the problems after I've added the titles.

**Comment by davidfarmer** [comment]
The WeBWorK problems are working for me.

All I did was 'make -B html'

**Comment by kentemorrison** [comment]
With 'make -B html' they're still hidden:

<img width="645" alt="screen shot 2018-01-31 at 4 35 28 pm" src="https://user-images.githubusercontent.com/6827944/35655246-bd64d0d6-06a5-11e8-966e-a52a0dacdc91.png">

**Comment by davidfarmer** [comment]
I don't understand why we get different results.  Let's sit
down together and look at what happens on each computer.

Ah, maybe it is the old knowls-from-local-computer problem.

Can you check if it works in Firefox?

**Comment by kentemorrison** [comment]
Works fine in Firefox. I was using Safari. Chrome also does not display the exercises. But Safari and Chrome display the exercise texts in the online version at activecalculus.org.
