### ISSUE TITLE
Alternate section 8.4, problem 5, sentence missing a word (maybe)

### ISSUE THREAD

**Issue by profh-variorum** [active-calculus/active-calculus-single-mbx#281]
In the _alternate_ chapter 8, section 8.4 problem 5 says

"As we **will in more detail** in the next section, we can use known Taylor series to obtain..."

I'm guessing this was meant to be "As we will see in more detail..." or something along those lines.

**Comment by mattboelkins** [comment]
Thanks for both of these comments; much appreciated.
MB
