### ISSUE TITLE
typo in NEW example 8.3.3

### ISSUE THREAD

**Issue by profh-variorum** [active-calculus/active-calculus-single-mbx#288]
My students and I found a typo yesterday in the new chapter 8.

In [example 8.3.3](
https://faculty.gvsu.edu/boelkinm/Home/ACS/sec-8a-3-geometric.html#Ex-8a-3-finite-geom-2), there is a finite geometric series. The general term is written as if it should be 2*(-4/3)^n, and the 0th term looks fine, but the terms for n=1, 2 and 3 are missing the factor of 2.

**Comment by mattboelkins** [comment]
Yes, thank you for pointing this out.  I've resolved this and will post the updated HTML later this summer.
