### ISSUE TITLE
Typo in example 7.5.1

### ISSUE THREAD

**Issue by profh-variorum** [active-calculus/active-calculus-single-mbx#290]
The description of [Example 7.5.1](https://activecalculus.org/single/sec-7-5-modeling.html#MBR) reads, "...construct a model for **how this type pollution** has built up in the lake." (emphasis added). 

Looks like it is missing "of".

**Comment by mattboelkins** [comment]
Indeed; thank you for all of your careful proofreading!

**Comment by mattboelkins** [comment]
fixed this typo
